package com.teag.reports;

import java.awt.Color;
import java.awt.Insets;

import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardPieItemLabelGenerator;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

import com.estate.pdf.CellInfo;
import com.estate.pdf.CellInfoFactory;
import com.estate.pdf.PageTable;
import com.estate.pdf.PageUtils;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.Image;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfWriter;
import com.teag.reports.GRATPages.CustomLabelGenerator;
import com.teag.reports.GRATPages.CustomToolTipGenerator;

public class LAPPages extends Page {

	double marketValue;
	double marketIncome;
	double estateTaxRate;
	double annualIncome;
	double annualIncomeRate;
	double incomeTax;
	double netIncome;
	double netSpendable;

	double lapIncome;
	double lapTax;
	double lapNetIncome;
	double lapInsPremium;
	double lapNetSpendable;
	double lapRatio;

	double lifeFaceValue;

	public LAPPages(Document document, PdfWriter writer) {
		super(document, writer);
		pageIcon = 2;
	}

	public void draw() {
		page1();
		newPage();
		page2();
		newPage();
		page3();
	}

	public double getAnnualIncome() {
		return annualIncome;
	}

	public double getAnnualIncomeRate() {
		return annualIncomeRate;
	}

	public double getEstateTaxRate() {
		return estateTaxRate;
	}

	public double getIncomeTax() {
		return incomeTax;
	}

	public double getLapIncome() {
		return lapIncome;
	}

	public double getLapInsPremium() {
		return lapInsPremium;
	}

	public double getLapNetIncome() {
		return lapNetIncome;
	}

	public double getLapNetSpendable() {
		return lapNetSpendable;
	}

	public double getLapRatio() {
		return lapRatio;
	}

	public double getLapTax() {
		return lapTax;
	}

	public double getLifeFaceValue() {
		return lifeFaceValue;
	}

	public double getMarketIncome() {
		return marketIncome;
	}

	public double getMarketValue() {
		return marketValue;
	}

	public double getNetIncome() {
		return netIncome;
	}

	public double getNetSpendable() {
		return netSpendable;
	}

	private void page1() {
		// Page 1
		Rectangle rct;

		drawBorder(pageIcon, "LAP");

		float ptSize = 12f;
		drawHeader(userInfo.getClientHeading(), "The Problem");
		String exp1 = "A we get older, we tend to be more inclined to have safe, liquid assets.  We often accumulate far more liquid assets than are needed for emergency and reserve purposes. These assets generally earn low interest rates and are fully subject to estate taxes.\n"
				+ "Liquid assets are not easily discounted by an LLC or family partnership.  Tax-deferred liquid assets, such as deferred annuities and retirement accounts, are also subject to income taxes, also known as Income in Respect of a Decedent (IRD).  This means they may be subject to two taxes, rather than just one, upon death.";

		String exp2 = "In most larger estates, all liquid assets in the estate are consumed in order to pay the taxes due on the entire assets of the estate.\n"
				+ "It is often possible to remove assets from the taxable estate without depriving the owners of the income or cash flow that is generated by the liquid assets.\n "
				+ "Let's examine a strategy that gives an immediate and 100% discount to liquid assets for puposes of valuing them for estate taxes, while also generating a cash flow income stream to the estate owner "
				+ "and a full benefit to the surviving family.";

		rct = drawLabel(exp1, prctTop, "GARA.TTF", new Color(0, 0, 0), ptSize,
				LBL_LEFT, LBL_TOP);
		drawLabel(exp2, prctLRight, "GARA.TTF", new Color(0, 0, 0), ptSize,
				LBL_LEFT, LBL_CENTER);

		// Now we need to display the table
		float left = rct.getLeft() + (rct.getWidth() * .125f);
		float right = rct.getRight() - (rct.getWidth() * .125f);

		rct.setLeft(left);
		rct.setRight(right);
		rct.setTop(rct.getBottom());
		rct.setBottom(prctTop.getBottom());

		// drawFilledRect(rct, new Color(128,255,128));
		drawLine(prctTop.getLeft(), horizLineY, prctTop.getRight(), horizLineY,
				new Color(0, 72, 117));

		PageTable table = new PageTable(writer);
		table.setTableFormat(rct, 2);
		float widths[] = { .75f, .25f };
		CellInfoFactory cif = new CellInfoFactory();
		BaseFont baseFont = PageUtils.LoadFont("GARA.TTF");
		BaseFont baseFontBold = PageUtils.LoadFont("GARABD.TTF");

		cif.setDefaultFont(new Font(baseFont, ptSize));
		Color green = new Color(0, 176, 0);
		Color red = new Color(192, 0, 0);
		CellInfo cellData[][] = {
				{
						cif.getCellInfo("Todays Fair Market Value"),
						cif.getCellInfo(dollar.format(marketValue),
								Element.ALIGN_RIGHT) },

				{
						cif.getCellInfo("Assumed Yeild"),
						cif.getCellInfo("" + percent.format(marketIncome),
								Element.ALIGN_RIGHT) },

				{
						cif.getCellInfo("Annual Spendable Cash"),
						cif.getCellInfo(number.format(marketValue
								* marketIncome), Element.ALIGN_RIGHT) },

				{ cif.getCellInfo(" "), cif.getCellInfo(" ") },

				{
						cif.getCellInfo(
								"Total Value (projected) in projected Estate",
								new Font(baseFontBold, ptSize, Font.NORMAL)),
						cif.getCellInfo(dollar.format(marketValue),
								Element.ALIGN_RIGHT, new Font(baseFontBold,
										ptSize, Font.NORMAL)) },

				{
						cif
								.getCellInfo("Estate Tax ("
										+ percent.format(estateTaxRate) + ")",
										new Font(baseFontBold, ptSize,
												Font.NORMAL, red)),
						cif.getCellInfo(dollar.format(estateTaxRate
								* marketValue), Element.ALIGN_RIGHT, new Font(
								baseFontBold, ptSize, Font.NORMAL, red)) },

				{
						cif.getCellInfo("Net Value Passing to Family",
								new Font(baseFontBold, ptSize, Font.NORMAL,
										green)),
						cif.getCellInfo(dollar.format(marketValue
								- (estateTaxRate * marketValue)),
								Element.ALIGN_RIGHT, new Font(baseFontBold,
										ptSize, Font.NORMAL, green)) } };
		// Do the chart

		table.setColumnWidths(widths);
		table.setTableData(cellData);
		table.drawTable();

		DefaultPieDataset dataset = new DefaultPieDataset();
		dataset.setValue("Estate Tax", estateTaxRate * marketValue);
		dataset.setValue("Net to Family", marketValue
				- (estateTaxRate * marketValue));

		PiePlot3D plot = new PiePlot3D(dataset);
		plot.setLabelGenerator(new StandardPieItemLabelGenerator());
		plot.setInsets(new Insets(0, 5, 5, 5));
		plot.setToolTipGenerator(new CustomToolTipGenerator());
		plot.setLabelGenerator(new CustomLabelGenerator());
		plot.setSectionPaint(0, red);
		plot.setSectionPaint(1, green);
		plot.setForegroundAlpha(.6f);
		plot.setOutlinePaint(Color.white);
		plot.setBackgroundPaint(Color.white);

		String title = "Asset";

		JFreeChart chart = new JFreeChart(title + " Distribution",
				JFreeChart.DEFAULT_TITLE_FONT, plot, true);

		chart.setBackgroundPaint(Color.white);
		chart.setAntiAlias(true);

		Rectangle page = prctLLeft;

		try {
			Image img = Image.getInstance(chart.createBufferedImage((int) page
					.getWidth(), (int) page.getHeight()), null);
			drawDiagram(img, prctLLeft, 0, 72);
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
	}

	private void page2() {
		Rectangle rct = new Rectangle(prctTop);
		drawBorder(pageIcon, "LAP");

		drawHeader(userInfo.getClientHeading(),
				"Liquid Asset Protection (LAP) Plan");

		// rct.setBottom(rct.getBottom() - Page._1_4TH);
		// rct.setLeft(rct.getLeft() - Page._1_4TH);
		drawDiagram("LapPlan2.png", rct, CNTR_LR + CNTR_TB);

		String theProcess[] = new String[] {
				"Liquid assets are transferred into a Single Premium Income Annuity (SPIA), which we refer to as a Guaranteed Income Contract (GIC).  It is a fully guaranteed contract issued by a highly rated insurance company.  The contract is usually owned directly by the estate owner(s).",
				"The contract pays a guaranteed cash flow to the owner for as long as he or she lives.  For a couple, this income can be guaranteed for both lives. Prior to life expectancy, as determined when the contract is purchased, most of the cash flow is tax-free (70-97%).  The amount of cash flow that is paid to the owners by the contract is quite high (usually 8-22% or more of the amount placed in the annuity contract).  This is not a yield, just the rate of the cash flow, and includes both interest and return of principal.",
				"The contract pays this cash flow only for as long as the owner(s) live(s).  Upon death(s), all cash flow ceases and the contract ends.  There is no residual value.  Hence, any money transferred into such a contract is removed from the estate upon the death(s) of the contract owner(s).",
				"For this reason, a life insurance policy is purchased with part of the annual cash flow coming from the contract.  The life insurance policy is designed to replace, tax free, the money transferred into the Guaranteed Income Contract.  The life insurance must be owned outside of the taxable estate in order to avoid being taxed as part of the estate.", };

		rct = new Rectangle(prctLeft);
		rct.setTop(rct.getTop() - Page._1_4TH * 12);
		drawSection(rct, "The Process", theProcess, 1);
		String benefits[];

		benefits = new String[] {
				"Liquid assets are immediately removed form the taxable estate.",
				"Estate taxes are immediately eliminated on the assets used to fund the LAP Plan. ",
				"IRD taxes are eliminated on tax deferred assets that are repositioned into the LAP Plan.",
				"Estate owners use cash flow from the income contract for living expenses and to fund the life insurance policy that will replace the Income Contract.  Almost always there is  more cash flow left over (after paying for the life insurance) than had been generated by the liquid assets before implementing the LAP Plan strategy. " };

		rct = new Rectangle(prctRight);
		rct.setTop(rct.getTop() - Page._1_4TH * 12);
		Rectangle r = drawSection(rct, "Benefits of using this technique",
				benefits, 2);
		String effects[];

		effects = new String[] {
				"Assets transferred into the LAP Plan become illiquid, except for the higher cash flow. In the process of removing these assets from the estate (and the resulting estate tax) they are no longer available for emergencies.",
				"The plan is permanent.  Although the life insurance policy may be altered or discontinued, the income contract is irreversible. ",
				"Until the point of life expectancy, as calculated at the inception of the LAP Plan, cash flow from the income contract is mostly tax free.  At life expectancy, the cash flow becomes fully subject to income taxes." };

		rct = new Rectangle(prctRight);
		rct.setTop(rct.getTop() - ((Page._1_4TH * 12) + r.getHeight()));
		r = drawSection(rct, "Side effects/Drawbacks of using this technique",
				effects, 2);
	}

	private void page3() {
		drawBorder(pageIcon, "LAP");
		drawHeader(userInfo.getClientHeading(),
				"Liquid Asset Protection (LAP) Plan");
		PageTable table = new PageTable(writer);
		table.setTableFormat(prctFull, 6);
		int Red = makeColor(192, 0, 0);
		int Green = makeColor(0, 192, 0);

		String cells[][] = {
				{
						"",
						"When comparing the results of leaving the asset in the Estate or placing in the Liquid Asset Preservation Plan, the difference is truly astounding.",
						"", "", "", "", "[][Colspan=5,ptSize=11][][][][]" },
				{ " ", "", "", "", "", "", "[colspan=6][][][][][]" },
				{
						"Cash Flow Analysis:",
						" ",
						"Results of " + percent.format(annualIncomeRate)
								+ " Asset",
						" ",
						"Results of LAP Plan",
						" ",
						"[colspan=2,bold=1,underline=1][][align=right,underline=1][][align=right,bold=1,underline=1][]" },
				{ "", "", "", "", "", "", "[colspan=6][][][][][]" },
				{ "", "Annual Cash Flow from Liquid Assets",
						"" + dollar.format(annualIncome), "",
						"" + dollar.format(this.lapIncome), "",
						"[][][][][bold=1][]" },
				{
						"",
						"Less Income Tax Due",
						"" + dollar.format(this.incomeTax),
						"",
						"" + dollar.format(this.lapTax),
						"",
						"[][Color=" + Red + "][underline=1,Color=" + Red
								+ "][][underline=1,Color=" + Red + "]" },
				{ "", "Net After Tax Income",
						"" + dollar.format(this.netIncome), "",
						"" + dollar.format(this.lapNetIncome), "",
						"[][][][][][]" },
				{ "", "Less Insurance Premium", "" + dollar.format(0.0), "",
						"" + dollar.format(this.lapInsPremium), "",
						"[][][underline=1][][underline=1][]" },
				{ "", "Net Spendable Cash Flow",
						"" + dollar.format(this.netSpendable), "",
						"" + dollar.format(this.lapNetSpendable), "",
						"[][][underline=1][][underline=1,bold=1][]" },
				{ "", "% of Asset Cash Flow Increase", "", "",
						"" + percent.format(this.lapRatio), "",
						"[][][][][color=" + Green + "][]" },
				{ " ", "", "", "", "", "", "[][][][][][]" },
				{ "Inheritance Analysis :", "", "", "", "", "",
						"[bold=1,underline=1,colspan=6][][][][][]" },
				{ "", "Liquid Asset Value", "" + dollar.format(marketValue),
						"", "" + dollar.format(lifeFaceValue), "",
						"[][][][][Bold=1][]" },
				{
						"",
						"Estate Tax Due ",
						""
								+ dollar.format(-1 * this.marketValue
										* this.estateTaxRate),
						"",
						"" + dollar.format(0),
						"",
						"[][color=" + Red + "][underline=1,color=" + Red
								+ "][][underline=1,bold=1][]" },
				{
						"",
						"Net To Family",
						""
								+ dollar.format(marketValue
										- (marketValue * estateTaxRate)), "",
						"" + dollar.format(lifeFaceValue), "",
						"[][][][][bold=1,underline=1][]" },
				{
						"",
						"% Increase to Family",
						"",
						"",
						""
								+ percent
										.format(lifeFaceValue
												/ (marketValue - (marketValue * estateTaxRate))),
						"",
						"[][color=" + Green + "][][][bold=1,color=" + Green
								+ "][]" },
				{ " ", "", "", "", "", "", "[colspan=6][][][][][]" },
				{ " ", "", "", "", "", "", "[colspan=6][][][][][]" },
				{ " ", "", "", "", "", "", "[colspan=6][][][][][]" },
				{ "Overcoming the Side Effects of the LAP Plan", "", "", "",
						"", "", "[bold=1,colspan=6][][][][][]" },
				{
						"1. When the exclusion ratio of the annuity wears off at the point of life expectancy, all future cash flow from the annuity will be fully taxable."
								+ " The premiums of the life insurance policy can often be structured in such a way that they may be decreased when the exclusion ratio ends."
								+ " Thus, when the cash flow from the annuity contract becomes fully taxable, the insurance premiums may decrease to partially, or fully, offset "
								+ "the increased income tax liability.", "",
						"", "", "", "", "[colspan=6][][][][][]" },
				{
						"2. If the life insurance policy used in the LAP Plan is owned by the estate owner, it will be part of the taxable estate."
								+ "  By having the policy owned in a trust, or other entity that is outside the estate, the life insurance benefit should be paid free of estate and income taxes.",
						"", "", "", "", "", "[colspan=6][][][][][]" },
				{
						"3.  During life, the LAP Plan turns liquid assets into non-assessable assets.  "
								+ ""
								+ "Upon death, however, the life insurance benefit becomes absolutely liquid. Assuming the policy proceeds pass to the family tax free, "
								+ ""
								+ "they replace the monies that were transferred into the guaranteed income contract and become immediately liquid again outside the taxable estate.  "
								+ "Thus, a liquid asset inside the estate is transferred outside the estate where it is also liquid.  "
								+ "In the meantime, the estate owners enjoy the cash flow from the asset at a level that is usually greater than they were experiencing prior to "
								+ "implementing the LAP Plan.", "", "", "", "",
						"", "[colspan=6][][][][][]" },
				{ " ", "", "", "", "", "", "[colspan=6][][][][][]" },
				{ "Notes :", "", "", "", "", "", "[bold=1,colspan=6][][][][][]" },
				{
						"",
						"1. Liquid assets are often non-growing assets.  They have a yield, but not a growth factor other than their yield. ",
						"", "", "", "", "[][colspan=5][][][][]" },

				{
						"",
						"2.	Some estate owners, who don't need this cash flow use it to fund a greater amount of life insurance in the trust, thus creating a guaranteed increase in the value of the assets transfered out of the estate by the LAP Plan.",
						"", "", "", "", "[][colspan=5][][][][]" },

				{
						"",
						"3.	The LAP Plan can be designed to provide an increased cash flow to the estate owners, or have an ultimate value to their families that is far more than the immediate value of the liquid assets transferred into the plan.  The plan can emphasize either current cash flow or ultimate inheritance value.",
						"", "", "", "", "[][colspan=5][][][][]" }, };
		float widths[] = { .05f, .40f, .225f, .05f, .225f, .05f };
		int alignments[] = { Element.ALIGN_LEFT, Element.ALIGN_LEFT,
				Element.ALIGN_RIGHT, Element.ALIGN_CENTER, Element.ALIGN_RIGHT,
				Element.ALIGN_LEFT };
		table.setColumnWidths(widths);
		table.setColumnAlignments(alignments);
		table.setFontSize(10);
		table.setTableFont("arial.TTF");
		table.setTableFontBold("arialbd.TTF");

		table.buildTableEx(cells);
		table.drawTable();

	}

	public void setAnnualIncome(double annualIncome) {
		this.annualIncome = annualIncome;
	}

	public void setAnnualIncomeRate(double annualIncomeRate) {
		this.annualIncomeRate = annualIncomeRate;
	}

	public void setEstateTaxRate(double estateTaxRate) {
		this.estateTaxRate = estateTaxRate;
	}

	public void setIncomeTax(double incomeTax) {
		this.incomeTax = incomeTax;
	}

	public void setLapIncome(double lapIncome) {
		this.lapIncome = lapIncome;
	}

	public void setLapInsPremium(double lapInsPremium) {
		this.lapInsPremium = lapInsPremium;
	}

	public void setLapNetIncome(double lapNetIncome) {
		this.lapNetIncome = lapNetIncome;
	}

	public void setLapNetSpendable(double lapNetSpendable) {
		this.lapNetSpendable = lapNetSpendable;
	}

	public void setLapRatio(double lapRatio) {
		this.lapRatio = lapRatio;
	}

	public void setLapTax(double lapTax) {
		this.lapTax = lapTax;
	}

	public void setLifeFaceValue(double lifeFaceValue) {
		this.lifeFaceValue = lifeFaceValue;
	}

	public void setMarketIncome(double marketIncome) {
		this.marketIncome = marketIncome;
	}

	public void setMarketValue(double marketValue) {
		this.marketValue = marketValue;
	}

	public void setNetIncome(double netIncome) {
		this.netIncome = netIncome;
	}

	public void setNetSpendable(double netSpendable) {
		this.netSpendable = netSpendable;
	}

}
