/*
 * Created on May 8, 2005
 *
 */
package com.teag.reports;

import com.lowagie.text.Document;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.PdfWriter;

/**
 * @author Paul R. Stay
 * 
 */
public class TCLAT2Pages extends Page {

	/**
	 * @param document
	 * @param writer
	 */

	public int term = 20; // Default
	public double amount = 0;
	public double charitableDeduction = 0;
	public double remainderInterest = 0;
	public double annuityPayment = 0;

	boolean useLLC = true;
	
	public TCLAT2Pages(Document document, PdfWriter writer) {
		super(document, writer);
		pageIcon = 2;

	}

	public void draw() {
		page1();
	}

	public double getAmount() {
		return amount;
	}

	public double getAnnuityPayment() {
		return annuityPayment;
	}

	public double getCharitableDeduction() {
		return charitableDeduction;
	}

	public double getRemainderInterest() {
		return remainderInterest;
	}

	public int getTerm() {
		return term;
	}

	public boolean isUseLLC() {
		return useLLC;
	}

	private void page1() {
		drawBorder(pageIcon, "Test. CLAT");
		drawHeader(userInfo.getClientHeading(), "Testamentary Charitable Lead Annuity Trust");
		if (userInfo.isSingle()) {
			if (userInfo.getClientGender().equalsIgnoreCase("M")) {
				if( useLLC) {
					drawDiagram("LLC-T-Clat-M.png", prctTop, 0);
				} else {
					drawDiagram("T-Clat-M.png", prctTop, 0);
				}
			} else {
				if( useLLC) {
					drawDiagram("LLC-T-Clat-F.png", prctTop, 0);
				} else {
					drawDiagram("T-Clat-F.png", prctTop, 0);
				}
			}
		} else {
			drawDiagram("T-Clat.png", prctTop, 0);
		}

		if (userInfo.isSingle()) {
			String sec1[] = {
					"Upon your death, a Testamentary Charitable Lead Annuity Trust (Test. CLAT) is funded with " + dollar.format(amount) + 
					" of assets. Your estate will receive a substantial deduction of " + dollar.format(charitableDeduction) +  
					" from the taxable estate based on the term of the trust, and the payout to charity.",
					"The family foundation (discussed next) and subsequently the charity(ies) of choice receive(s) a fixed annual payment for "
							+ Integer.toString(term) 
							+ " years from the income generated by the use of assets transferred to the Test. CLAT.",
					"At the end of the Test. CLAT term, the assets plus any appreciation pass estate-tax free to the family." };

			String benefits[] = {
					"A substantial discount is obtained by your estate through utilizing the Test. CLAT.",
					userInfo.getClientFirstName()
							+ " has full control of assets while living, and can choose the level of control by the family after death.",
					"Full value of the assets is later transferred to the family without additional tax.",
					"Excess earnings and growth in the value of assets add to the benefit to the family.",
					"The substantial tax savings are shared by the family and selected charities.",
					"Assets transferred to the Test. CLAT receive a step up in basis."

			};

			String effects[] = { "Heirs do not receive the benefit of the assets until after the CLAT term expires." };

			drawSection(prctLLeft, " ", sec1, 1);
			Rectangle rctx = new Rectangle(prctLRight);
			rctx.setRight(rctx.getRight() + _1_2TH);
			rctx = this.drawSection(rctx, "Benefits of Using this Technique",
					benefits, 2);

			Rectangle rct = new Rectangle(prctLRight);
			rct.setRight(rct.getRight() + _1_2TH);
			rct.setTop(rctx.getBottom());

			drawSection(rct,
					"Side Effects / Draw backs of using this technique",
					effects, 2);
		} else {
			String sec1[] = {
					"Upon both of your deaths, a Testamentary Charitable Lead Annuity Trust (Test. CLAT), which will be described in your Living Trust," +
					"is funded with " + dollar.format(amount) + " of assets. " +
					"Your estate will receive a substantial deduction of " + dollar.format(charitableDeduction) +" from the taxable estate based on the term of the trust " + 
					"and the payout to charity.",
					"A family foundation and subsequently the charity(ies) of choice receive(s) a fixed annual payment of " +  dollar.format(annuityPayment) + " for "
							+ Integer.toString(term) +
					" years from the income generated by the use of assets transferred to the Test. CLAT.",
					"At the end of the Test. CLAT term, the assets plus any appreciation pass estate-tax free to the family." };

			String benefits[] = {
					"A substantial discount is obtained by your estate through utilizing the Test. CLAT.",
					clientFirstName
							+ " and "
							+ spouseFirstName
							+ " have full control of assets while living, and can choose the level of control by the family after death.",
					"Full value of the assets is later transferred to the family without additional tax.",
					"Excess earnings and growth in the value of assets add to the benefit to the family.",
					"The substantial tax savings are shared by the family and selected charities.",
					"Assets transferred to Test. CLAT receive a step up in basis."

			};

			String effects[] = { "Heirs do not receive the benefit of the assets until after the CLAT term expires." };

			drawSection(prctLLeft, " ", sec1, 1);
			Rectangle rctx = new Rectangle(prctLRight);
			rctx.setRight(rctx.getRight() + _1_2TH);
			rctx = drawSection(rctx, "Benefits of Using this Technique",
					benefits, 2);

			Rectangle rct = new Rectangle(prctLRight);
			rct.setRight(rct.getRight() + _1_2TH);
			rct.setTop(rctx.getBottom());

			drawSection(rct,
					"Side Effects / Draw backs of using this technique",
					effects, 2);
		}

	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public void setAnnuityPayment(double annuityPayment) {
		this.annuityPayment = annuityPayment;
	}

	public void setCharitableDeduction(double charitableDeduction) {
		this.charitableDeduction = charitableDeduction;
	}

	public void setRemainderInterest(double remainderInterest) {
		this.remainderInterest = remainderInterest;
	}

	public void setTerm(int term) {
		this.term = term;
	}

	public void setUseLLC(boolean useLLC) {
		this.useLLC = useLLC;
	}
}
